# AUTO-GENERATED from Bitext dataset. Do not edit manually.
FEW_SHOT_EXAMPLES = [
    {"instruction": "I cannot afford purchase {{Order Number}}", "intent": "cancel_order", "category": "ORDER"},
    {"instruction": "I have bought some item, I have to cancel order {{Order Number}}", "intent": "cancel_order", "category": "ORDER"},
    {"instruction": "I do not want this item, cancel order {{Order Number}}", "intent": "cancel_order", "category": "ORDER"},
    {"instruction": "I need assistance with canceling purchase {{Order Number}}", "intent": "cancel_order", "category": "ORDER"},
    {"instruction": "were can i cancel purchase {{Order Number}}", "intent": "cancel_order", "category": "ORDER"},
    {"instruction": "want assistance to cancel order {{Order Number}}", "intent": "cancel_order", "category": "ORDER"},
    {"instruction": "I don't know what to do to cancel purchase {{Order Number}}", "intent": "cancel_order", "category": "ORDER"},
    {"instruction": "i cannot pay for my last item cancel order {{Order Number}}", "intent": "cancel_order", "category": "ORDER"},
    {"instruction": "I want help to cancel purchase {{Order Number}}", "intent": "cancel_order", "category": "ORDER"},
    {"instruction": "I need help with cancelling purhase {{Order Number}}", "intent": "cancel_order", "category": "ORDER"},
    {"instruction": "I have to delete several items from purchase {{Order Number}}", "intent": "change_order", "category": "ORDER"},
    {"instruction": "updating purchase {{Order Number}}", "intent": "change_order", "category": "ORDER"},
    {"instruction": "update purchase00123842", "intent": "change_order", "category": "ORDER"},
    {"instruction": "I want assistance editing purchase  {{Order Number}}", "intent": "change_order", "category": "ORDER"},
    {"instruction": "I have to delete an item from order {{Order Number}}", "intent": "change_order", "category": "ORDER"},
    {"instruction": "i need information about correcting purchase {{Order Number}}", "intent": "change_order", "category": "ORDER"},
    {"instruction": "update purcahse {{Order Number}}", "intent": "change_order", "category": "ORDER"},
    {"instruction": "help switching something of purchase {{Order Number}}", "intent": "change_order", "category": "ORDER"},
    {"instruction": "I cannot add a product to purchase {{Order Number}}", "intent": "change_order", "category": "ORDER"},
    {"instruction": "editing order {{Order Number}}", "intent": "change_order", "category": "ORDER"},
    {"instruction": "there is an issue trying to update the address", "intent": "change_shipping_address", "category": "SHIPPING"},
    {"instruction": "I cannot edit my delivery address", "intent": "change_shipping_address", "category": "SHIPPING"},
    {"instruction": "I want assistance updating my delivery address", "intent": "change_shipping_address", "category": "SHIPPING"},
    {"instruction": "i want information about correcting the shiping address", "intent": "change_shipping_address", "category": "SHIPPING"},
    {"instruction": "I entered a wrong delivery address, help me editing it", "intent": "change_shipping_address", "category": "SHIPPING"},
    {"instruction": "I have a trouble correcing the address", "intent": "change_shipping_address", "category": "SHIPPING"},
    {"instruction": "I have an error updating my address", "intent": "change_shipping_address", "category": "SHIPPING"},
    {"instruction": "problems with a delivery address modification", "intent": "change_shipping_address", "category": "SHIPPING"},
    {"instruction": "I want to modify the address, how can I do it?", "intent": "change_shipping_address", "category": "SHIPPING"},
    {"instruction": "I have entered a wrong delivery address, help me changing it", "intent": "change_shipping_address", "category": "SHIPPING"},
    {"instruction": "I am tring to see the early exit penalty", "intent": "check_cancellation_fee", "category": "CANCEL"},
    {"instruction": "check cancellation fee", "intent": "check_cancellation_fee", "category": "CANCEL"},
    {"instruction": "I do not know how to check the cancellation charge", "intent": "check_cancellation_fee", "category": "CANCEL"},
    {"instruction": "I want help to see the early exit fees", "intent": "check_cancellation_fee", "category": "CANCEL"},
    {"instruction": "checking early exit fee", "intent": "check_cancellation_fee", "category": "CANCEL"},
    {"instruction": "i have to check the cancellation penalty", "intent": "check_cancellation_fee", "category": "CANCEL"},
    {"instruction": "I don't know what I have to do to see the termination fees", "intent": "check_cancellation_fee", "category": "CANCEL"},
    {"instruction": "I have got to check the early exit fee", "intent": "check_cancellation_fee", "category": "CANCEL"},
    {"instruction": "help seeing the withdrawal fee", "intent": "check_cancellation_fee", "category": "CANCEL"},
    {"instruction": "I cannot find the termination penalty, can I get some help?", "intent": "check_cancellation_fee", "category": "CANCEL"},
    {"instruction": "I need assistance to take a quick look at bill #85632", "intent": "check_invoice", "category": "INVOICE"},
    {"instruction": "hepp seeing the bill from {{Person Name}}", "intent": "check_invoice", "category": "INVOICE"},
    {"instruction": "how do I check my bill from {{Person Name}}?", "intent": "check_invoice", "category": "INVOICE"},
    {"instruction": "want assistance to give a quick look at the invoice #12588", "intent": "check_invoice", "category": "INVOICE"},
    {"instruction": "I don't know what to do ti see my invoice from {{Person Name}}", "intent": "check_invoice", "category": "INVOICE"},
    {"instruction": "chcek bills from {{Person Name}}", "intent": "check_invoice", "category": "INVOICE"},
    {"instruction": "I can't locate my invoices from {{Person Name}}", "intent": "check_invoice", "category": "INVOICE"},
    {"instruction": "need to chek my bill #85632 how to do it", "intent": "check_invoice", "category": "INVOICE"},
    {"instruction": "check invoices from last purchase", "intent": "check_invoice", "category": "INVOICE"},
    {"instruction": "wanna find the invoices from {{Person Name}} how can i do it", "intent": "check_invoice", "category": "INVOICE"},
    {"instruction": "can I see what payment methods are available?", "intent": "check_payment_methods", "category": "PAYMENT"},
    {"instruction": "I want assistance to check the goddamn payment methods", "intent": "check_payment_methods", "category": "PAYMENT"},
    {"instruction": "I don't know how I can list the allowed payment methods", "intent": "check_payment_methods", "category": "PAYMENT"},
    {"instruction": "i want assistance to list the payment methods", "intent": "check_payment_methods", "category": "PAYMENT"},
    {"instruction": "can you tell me your damn payment methods?", "intent": "check_payment_methods", "category": "PAYMENT"},
    {"instruction": "assistance to list your paymernt modalities", "intent": "check_payment_methods", "category": "PAYMENT"},
    {"instruction": "see your payment modalities", "intent": "check_payment_methods", "category": "PAYMENT"},
    {"instruction": "can you tell me your allowed payment modalities?", "intent": "check_payment_methods", "category": "PAYMENT"},
    {"instruction": "where can I see what payment methods are accepted?", "intent": "check_payment_methods", "category": "PAYMENT"},
    {"instruction": "I have to list the payment modalities, I need assistance", "intent": "check_payment_methods", "category": "PAYMENT"},
    {"instruction": "I try to check in which situations can I ask for a refund", "intent": "check_refund_policy", "category": "REFUND"},
    {"instruction": "need assistance to check ur reimbursement policy", "intent": "check_refund_policy", "category": "REFUND"},
    {"instruction": "I need help seeing in which cases can I ask for a reufnd", "intent": "check_refund_policy", "category": "REFUND"},
    {"instruction": "how to check ur refund policy", "intent": "check_refund_policy", "category": "REFUND"},
    {"instruction": "need assistance seeing in which cases can i request a refund", "intent": "check_refund_policy", "category": "REFUND"},
    {"instruction": "help me check in which cvases can i ask for my money back", "intent": "check_refund_policy", "category": "REFUND"},
    {"instruction": "i want help to check in what cases can i request refunds", "intent": "check_refund_policy", "category": "REFUND"},
    {"instruction": "need help to see in which situations can I request a refund", "intent": "check_refund_policy", "category": "REFUND"},
    {"instruction": "can you help me checking your reimbursement policy?", "intent": "check_refund_policy", "category": "REFUND"},
    {"instruction": "help me to see in which cases can i ask for my money back", "intent": "check_refund_policy", "category": "REFUND"},
    {"instruction": "I have to make a consumer reclamation against your company", "intent": "complaint", "category": "FEEDBACK"},
    {"instruction": "could you help me file a customer reclamation?", "intent": "complaint", "category": "FEEDBACK"},
    {"instruction": "where to lodge a complaint?", "intent": "complaint", "category": "FEEDBACK"},
    {"instruction": "file customerr claim", "intent": "complaint", "category": "FEEDBACK"},
    {"instruction": "assistance to file a claim", "intent": "complaint", "category": "FEEDBACK"},
    {"instruction": "assistance to file a customer claim", "intent": "complaint", "category": "FEEDBACK"},
    {"instruction": "I do not know what I have to do to make a reclamation", "intent": "complaint", "category": "FEEDBACK"},
    {"instruction": "I need to make a damn consumer complaint, how could I do it?", "intent": "complaint", "category": "FEEDBACK"},
    {"instruction": "can you help me lodging a claim against your business ?", "intent": "complaint", "category": "FEEDBACK"},
    {"instruction": "help to make a customer complaint", "intent": "complaint", "category": "FEEDBACK"},
    {"instruction": "help to check what hours customer assistance available is", "intent": "contact_customer_service", "category": "CONTACT"},
    {"instruction": "where do I check what hours I can reach customer service?", "intent": "contact_customer_service", "category": "CONTACT"},
    {"instruction": "how do I see at what time customer assistance available is?", "intent": "contact_customer_service", "category": "CONTACT"},
    {"instruction": "I do not know how to get in touch with customer assistance", "intent": "contact_customer_service", "category": "CONTACT"},
    {"instruction": "could i get in touchwith customer service", "intent": "contact_customer_service", "category": "CONTACT"},
    {"instruction": "want help to check what hours i cancall customer service", "intent": "contact_customer_service", "category": "CONTACT"},
    {"instruction": "I'm trying to check what hours i can reach customer suport", "intent": "contact_customer_service", "category": "CONTACT"},
    {"instruction": "I have to speak with customer support, how can I do it?", "intent": "contact_customer_service", "category": "CONTACT"},
    {"instruction": "wannaspeak with customer service can ya help me", "intent": "contact_customer_service", "category": "CONTACT"},
    {"instruction": "where to see what hours I can contact customer support?", "intent": "contact_customer_service", "category": "CONTACT"},
    {"instruction": "I can't speak iwth an operator", "intent": "contact_human_agent", "category": "CONTACT"},
    {"instruction": "I want help to talk with a human agent", "intent": "contact_human_agent", "category": "CONTACT"},
    {"instruction": "i try to talk with a person", "intent": "contact_human_agent", "category": "CONTACT"},
    {"instruction": "can you help me talking with someone?", "intent": "contact_human_agent", "category": "CONTACT"},
    {"instruction": "i want help talking with a human agent", "intent": "contact_human_agent", "category": "CONTACT"},
    {"instruction": "assistance contacting a person", "intent": "contact_human_agent", "category": "CONTACT"},
    {"instruction": "want assistance talking to an operator", "intent": "contact_human_agent", "category": "CONTACT"},
    {"instruction": "i want help talking with an assistat", "intent": "contact_human_agent", "category": "CONTACT"},
    {"instruction": "want help to speak to someone", "intent": "contact_human_agent", "category": "CONTACT"},
    {"instruction": "talking to agent", "intent": "contact_human_agent", "category": "CONTACT"},
    {"instruction": "new {{Account Category}} acount for wife", "intent": "create_account", "category": "ACCOUNT"},
    {"instruction": "help me creating a freemium account", "intent": "create_account", "category": "ACCOUNT"},
    {"instruction": "i have a problem with opening a {{Account Category}} account", "intent": "create_account", "category": "ACCOUNT"},
    {"instruction": "i aint registered yet assistance creating a {{Account Type}} account", "intent": "create_account", "category": "ACCOUNT"},
    {"instruction": "open pro account for wife", "intent": "create_account", "category": "ACCOUNT"},
    {"instruction": "i do not know how to create a {{Account Category}} account", "intent": "create_account", "category": "ACCOUNT"},
    {"instruction": "I don't have a bloody standard account, can I open one?", "intent": "create_account", "category": "ACCOUNT"},
    {"instruction": "create new {{Account Type}} account for daughter", "intent": "create_account", "category": "ACCOUNT"},
    {"instruction": "another premium account for father", "intent": "create_account", "category": "ACCOUNT"},
    {"instruction": "want assistance opening a platinum account for my dad", "intent": "create_account", "category": "ACCOUNT"},
    {"instruction": "I want assistance removing my goddamn platinum account", "intent": "delete_account", "category": "ACCOUNT"},
    {"instruction": "i want help to close my {{Account Category}} accouny", "intent": "delete_account", "category": "ACCOUNT"},
    {"instruction": "could uhelp me close a freemium account", "intent": "delete_account", "category": "ACCOUNT"},
    {"instruction": "I have a question about the deletion of my {{Account Type}} account", "intent": "delete_account", "category": "ACCOUNT"},
    {"instruction": "I don't need my damn standard account, I have to remove it", "intent": "delete_account", "category": "ACCOUNT"},
    {"instruction": "I do not know what I have to do to remove a {{Account Type}} account", "intent": "delete_account", "category": "ACCOUNT"},
    {"instruction": "is it possible to delete the standard account?", "intent": "delete_account", "category": "ACCOUNT"},
    {"instruction": "how can I delete the standard account?", "intent": "delete_account", "category": "ACCOUNT"},
    {"instruction": "i do not nkow how to delete the premium account", "intent": "delete_account", "category": "ACCOUNT"},
    {"instruction": "remove platinum account", "intent": "delete_account", "category": "ACCOUNT"},
    {"instruction": "can I place an ordewr from {{Delivery Country}}?", "intent": "delivery_options", "category": "DELIVERY"},
    {"instruction": "help to check what methods for delivery i have", "intent": "delivery_options", "category": "DELIVERY"},
    {"instruction": "do you shp to {{Delivery City}}?", "intent": "delivery_options", "category": "DELIVERY"},
    {"instruction": "is it possible to place an order from {{Delivery City}}?", "intent": "delivery_options", "category": "DELIVERY"},
    {"instruction": "I am trying to check what delivery methods you offer", "intent": "delivery_options", "category": "DELIVERY"},
    {"instruction": "wanna see what delivery options are there i need help", "intent": "delivery_options", "category": "DELIVERY"},
    {"instruction": "I need to see what delivery methods you offer, help me", "intent": "delivery_options", "category": "DELIVERY"},
    {"instruction": "show me what shipping options you offer", "intent": "delivery_options", "category": "DELIVERY"},
    {"instruction": "I want information about the delivery methods", "intent": "delivery_options", "category": "DELIVERY"},
    {"instruction": "I have got to check what delivery methods are there", "intent": "delivery_options", "category": "DELIVERY"},
    {"instruction": "I need assistance checking how soon can I expect my delivery", "intent": "delivery_period", "category": "DELIVERY"},
    {"instruction": "help to check how soon can I expect my shipment", "intent": "delivery_period", "category": "DELIVERY"},
    {"instruction": "is it possible to check when my shipment is going to arrive?", "intent": "delivery_period", "category": "DELIVERY"},
    {"instruction": "is it possible to see when my product is going to arrive?", "intent": "delivery_period", "category": "DELIVERY"},
    {"instruction": "I'm calling to check whenb will my item arrive", "intent": "delivery_period", "category": "DELIVERY"},
    {"instruction": "is it possible to check how soon can I expect the item?", "intent": "delivery_period", "category": "DELIVERY"},
    {"instruction": "I have to see when my item is going to arrive, help me", "intent": "delivery_period", "category": "DELIVERY"},
    {"instruction": "need help to see how long it takes for my parcel to arrive", "intent": "delivery_period", "category": "DELIVERY"},
    {"instruction": "I want to see when will my product arrive", "intent": "delivery_period", "category": "DELIVERY"},
    {"instruction": "where do i check how long it takes for my shipment to arrive", "intent": "delivery_period", "category": "DELIVERY"},
    {"instruction": "update information on {{Account Category}} account", "intent": "edit_account", "category": "ACCOUNT"},
    {"instruction": "how to correct some of the details on my user profile", "intent": "edit_account", "category": "ACCOUNT"},
    {"instruction": "correcting information on premium account", "intent": "edit_account", "category": "ACCOUNT"},
    {"instruction": "update details on premium account", "intent": "edit_account", "category": "ACCOUNT"},
    {"instruction": "how to update the info on my user profile?", "intent": "edit_account", "category": "ACCOUNT"},
    {"instruction": "changing data on standard  account", "intent": "edit_account", "category": "ACCOUNT"},
    {"instruction": "help to change soe of the details on my profile", "intent": "edit_account", "category": "ACCOUNT"},
    {"instruction": "correcting data on platinum account", "intent": "edit_account", "category": "ACCOUNT"},
    {"instruction": "editing freemium  account", "intent": "edit_account", "category": "ACCOUNT"},
    {"instruction": "I'd like to edit the data included on my user i need help", "intent": "edit_account", "category": "ACCOUNT"},
    {"instruction": "i have got to get bill #37777 how to do it", "intent": "get_invoice", "category": "INVOICE"},
    {"instruction": "i do not know what i need to do to get my invoice #85632", "intent": "get_invoice", "category": "INVOICE"},
    {"instruction": "assistance to get my bills from {{Person Name}}", "intent": "get_invoice", "category": "INVOICE"},
    {"instruction": "what do i need to do to get my invoices from {{Person Name}}", "intent": "get_invoice", "category": "INVOICE"},
    {"instruction": "what od i have to do to download bill #00108", "intent": "get_invoice", "category": "INVOICE"},
    {"instruction": "I want assistance downloading invoice #00108", "intent": "get_invoice", "category": "INVOICE"},
    {"instruction": "I don't know what to do to download my invoice #12588", "intent": "get_invoice", "category": "INVOICE"},
    {"instruction": "I need help downloading the bills from {{Person Name}}", "intent": "get_invoice", "category": "INVOICE"},
    {"instruction": "i dont know what i need to do to download invoice #12588", "intent": "get_invoice", "category": "INVOICE"},
    {"instruction": "mail me my invoices from {{Person Name}}", "intent": "get_invoice", "category": "INVOICE"},
    {"instruction": "I paid {{Currency Symbol}}{{Refund Amount}} for this product, I need to get a rebate", "intent": "get_refund", "category": "REFUND"},
    {"instruction": "I am trying to receive a compensation", "intent": "get_refund", "category": "REFUND"},
    {"instruction": "i need assistance demanding compensations of my money", "intent": "get_refund", "category": "REFUND"},
    {"instruction": "I try to ask fopr a refund of my money", "intent": "get_refund", "category": "REFUND"},
    {"instruction": "need assistance to obtain a refund of my money", "intent": "get_refund", "category": "REFUND"},
    {"instruction": "I am trying to request compensations of money", "intent": "get_refund", "category": "REFUND"},
    {"instruction": "could you help me obtain rebates of money?", "intent": "get_refund", "category": "REFUND"},
    {"instruction": "i have paid {{Currency Symbol}}{{Refund Amount}} for a product where to get my money back", "intent": "get_refund", "category": "REFUND"},
    {"instruction": "I have got to ask for rebates", "intent": "get_refund", "category": "REFUND"},
    {"instruction": "rebating  {{Currency Symbol}}{{Refund Amount}}", "intent": "get_refund", "category": "REFUND"},
    {"instruction": "i want assistance unsubscribing from the newsletter", "intent": "newsletter_subscription", "category": "SUBSCRIPTION"},
    {"instruction": "I need to unsubscribe from the newsletter, can yyou help me?", "intent": "newsletter_subscription", "category": "SUBSCRIPTION"},
    {"instruction": "can uhelp me subscribe to ur newsletter", "intent": "newsletter_subscription", "category": "SUBSCRIPTION"},
    {"instruction": "I acn't unsubscribe to your company newsletter", "intent": "newsletter_subscription", "category": "SUBSCRIPTION"},
    {"instruction": "I want help receoving the newsletter", "intent": "newsletter_subscription", "category": "SUBSCRIPTION"},
    {"instruction": "information about receiving your company newsletter", "intent": "newsletter_subscription", "category": "SUBSCRIPTION"},
    {"instruction": "I have to receive your corporate newsletter, help me", "intent": "newsletter_subscription", "category": "SUBSCRIPTION"},
    {"instruction": "can I unsubscribe to your corporate newsletter?", "intent": "newsletter_subscription", "category": "SUBSCRIPTION"},
    {"instruction": "I need to receive thecorporate newsletter", "intent": "newsletter_subscription", "category": "SUBSCRIPTION"},
    {"instruction": "I can't receive the company newsletter", "intent": "newsletter_subscription", "category": "SUBSCRIPTION"},
    {"instruction": "can you help me reporting problems with online payment?", "intent": "payment_issue", "category": "PAYMENT"},
    {"instruction": "assistance to notify of issues with online payments", "intent": "payment_issue", "category": "PAYMENT"},
    {"instruction": "i cant make payments how to inform of issues with payment", "intent": "payment_issue", "category": "PAYMENT"},
    {"instruction": "I cannot make a payment, I want help to report a problem", "intent": "payment_issue", "category": "PAYMENT"},
    {"instruction": "how do I notify of an issue with payment?", "intent": "payment_issue", "category": "PAYMENT"},
    {"instruction": "where do i inform of a trouble with payments", "intent": "payment_issue", "category": "PAYMENT"},
    {"instruction": "the payment did not go through, report an error", "intent": "payment_issue", "category": "PAYMENT"},
    {"instruction": "the payment failed, how to report an error with payment?", "intent": "payment_issue", "category": "PAYMENT"},
    {"instruction": "i dont know what i have to do to report issues with payments", "intent": "payment_issue", "category": "PAYMENT"},
    {"instruction": "notify of trouble with online payments", "intent": "payment_issue", "category": "PAYMENT"},
    {"instruction": "I want assistance doing a purchase", "intent": "place_order", "category": "ORDER"},
    {"instruction": "I have to shop a few of your product, how could I do it?", "intent": "place_order", "category": "ORDER"},
    {"instruction": "I have to buy some of yout item", "intent": "place_order", "category": "ORDER"},
    {"instruction": "need assistance purchasing some of ur article", "intent": "place_order", "category": "ORDER"},
    {"instruction": "i dont know what i have to do to buy an article", "intent": "place_order", "category": "ORDER"},
    {"instruction": "where to earn several of your product?", "intent": "place_order", "category": "ORDER"},
    {"instruction": "I don't know what I have to do to shop a few of your item", "intent": "place_order", "category": "ORDER"},
    {"instruction": "I need help acquiringv several of your item", "intent": "place_order", "category": "ORDER"},
    {"instruction": "I want help to earn something", "intent": "place_order", "category": "ORDER"},
    {"instruction": "I need to shop a few of your product, how can I do it?", "intent": "place_order", "category": "ORDER"},
    {"instruction": "can you help me recover the key of my profile?", "intent": "recover_password", "category": "ACCOUNT"},
    {"instruction": "I need help restoring the PIN of my profile", "intent": "recover_password", "category": "ACCOUNT"},
    {"instruction": "where can i get information about the pwd reset", "intent": "recover_password", "category": "ACCOUNT"},
    {"instruction": "I am looking for information about a forgotten key", "intent": "recover_password", "category": "ACCOUNT"},
    {"instruction": "i have to resdet my user pin code", "intent": "recover_password", "category": "ACCOUNT"},
    {"instruction": "want assistance to retrieve the pin code of my user profile", "intent": "recover_password", "category": "ACCOUNT"},
    {"instruction": "i need information about a pwd recovery", "intent": "recover_password", "category": "ACCOUNT"},
    {"instruction": "i need help to reset the pwd of m account", "intent": "recover_password", "category": "ACCOUNT"},
    {"instruction": "I try to restore my user profile PIN", "intent": "recover_password", "category": "ACCOUNT"},
    {"instruction": "I don't know what to do to reset my user PIN code", "intent": "recover_password", "category": "ACCOUNT"},
    {"instruction": "i dont know how to report signup issues", "intent": "registration_problems", "category": "ACCOUNT"},
    {"instruction": "assistance opening user account", "intent": "registration_problems", "category": "ACCOUNT"},
    {"instruction": "need assistance to notify of errors with a registration", "intent": "registration_problems", "category": "ACCOUNT"},
    {"instruction": "help to  inform of a problem with a registration", "intent": "registration_problems", "category": "ACCOUNT"},
    {"instruction": "I cannot open a user, I have to inform of a signup issue", "intent": "registration_problems", "category": "ACCOUNT"},
    {"instruction": "help me to inform of a registration issue", "intent": "registration_problems", "category": "ACCOUNT"},
    {"instruction": "i cannot sign up i need to report sign-up problems", "intent": "registration_problems", "category": "ACCOUNT"},
    {"instruction": "i want help regarding my sign-up", "intent": "registration_problems", "category": "ACCOUNT"},
    {"instruction": "assistance informing of an error with a signup", "intent": "registration_problems", "category": "ACCOUNT"},
    {"instruction": "help me to informof an issue with a registration", "intent": "registration_problems", "category": "ACCOUNT"},
    {"instruction": "I am calling to leave my feedback for your products", "intent": "review", "category": "FEEDBACK"},
    {"instruction": "want help sending feedback about a service", "intent": "review", "category": "FEEDBACK"},
    {"instruction": "i call to write an opinion about an product", "intent": "review", "category": "FEEDBACK"},
    {"instruction": "is there a method to submit a review for ur company", "intent": "review", "category": "FEEDBACK"},
    {"instruction": "do you have a method to leave a review about a service?", "intent": "review", "category": "FEEDBACK"},
    {"instruction": "I need to send some feedback for a service, how to do it?", "intent": "review", "category": "FEEDBACK"},
    {"instruction": "I do not know how I can send some feedback for your company", "intent": "review", "category": "FEEDBACK"},
    {"instruction": "I have got to submit my feedback", "intent": "review", "category": "FEEDBACK"},
    {"instruction": "help me writing a comment for a service", "intent": "review", "category": "FEEDBACK"},
    {"instruction": "is there a e-mail to send my feedback for your products?", "intent": "review", "category": "FEEDBACK"},
    {"instruction": "i want help submitting a different delivery address", "intent": "set_up_shipping_address", "category": "SHIPPING"},
    {"instruction": "error submitting my shipping address", "intent": "set_up_shipping_address", "category": "SHIPPING"},
    {"instruction": "there is a trouble setting another delivery address up", "intent": "set_up_shipping_address", "category": "SHIPPING"},
    {"instruction": "there is an issue submitting the new delivery address", "intent": "set_up_shipping_address", "category": "SHIPPING"},
    {"instruction": "I have to enter the shipping address, how do I do it?", "intent": "set_up_shipping_address", "category": "SHIPPING"},
    {"instruction": "I need to submit my delivery address", "intent": "set_up_shipping_address", "category": "SHIPPING"},
    {"instruction": "I have got to submit the new shipping address, I need help", "intent": "set_up_shipping_address", "category": "SHIPPING"},
    {"instruction": "could you help me setting up my new delivery address?", "intent": "set_up_shipping_address", "category": "SHIPPING"},
    {"instruction": "I need assistance to set the delivery address up", "intent": "set_up_shipping_address", "category": "SHIPPING"},
    {"instruction": "can you help me setting another delivery addrss up?", "intent": "set_up_shipping_address", "category": "SHIPPING"},
    {"instruction": "how to use tye {{Account Type}} account?", "intent": "switch_account", "category": "ACCOUNT"},
    {"instruction": "i cant switch to the premium account", "intent": "switch_account", "category": "ACCOUNT"},
    {"instruction": "I do not know how I can change to the {{Account Category}} account", "intent": "switch_account", "category": "ACCOUNT"},
    {"instruction": "can I use the {{Account Type}} profile?", "intent": "switch_account", "category": "ACCOUNT"},
    {"instruction": "what do i need to do to use the premium profile", "intent": "switch_account", "category": "ACCOUNT"},
    {"instruction": "can I change to the {{Account Category}} account?", "intent": "switch_account", "category": "ACCOUNT"},
    {"instruction": "I want assistance switching to the premium account", "intent": "switch_account", "category": "ACCOUNT"},
    {"instruction": "i need assistance switching to the {{Account Type}} account", "intent": "switch_account", "category": "ACCOUNT"},
    {"instruction": "help changing to the {{Account Category}} account", "intent": "switch_account", "category": "ACCOUNT"},
    {"instruction": "i want help to use the {{Account Category}} profile", "intent": "switch_account", "category": "ACCOUNT"},
    {"instruction": "where to see the bloody ETA of the order {{Order Number}}", "intent": "track_order", "category": "ORDER"},
    {"instruction": "checking status of order {{Order Number}}", "intent": "track_order", "category": "ORDER"},
    {"instruction": "see purchase {{Order Number}} current status", "intent": "track_order", "category": "ORDER"},
    {"instruction": "how can i see order {{Order Number}} status", "intent": "track_order", "category": "ORDER"},
    {"instruction": "help seeing the ETA of order {{Order Number}}", "intent": "track_order", "category": "ORDER"},
    {"instruction": "help to see thje ETA of purchase {{Order Number}}", "intent": "track_order", "category": "ORDER"},
    {"instruction": "i do not kno what to do to locate purchase {{Order Number}}", "intent": "track_order", "category": "ORDER"},
    {"instruction": "assistance to see order {{Order Number}} current status", "intent": "track_order", "category": "ORDER"},
    {"instruction": "see order {{Order Number}} fucking current status", "intent": "track_order", "category": "ORDER"},
    {"instruction": "I want help seeing the status of order {{Order Number}}", "intent": "track_order", "category": "ORDER"},
    {"instruction": "i expect a rebate of {{Currency Symbol}}{{Refund Amount}}", "intent": "track_refund", "category": "REFUND"},
    {"instruction": "I am waiting for a restitution of {{Currency Symbol}}{{Refund Amount}}", "intent": "track_refund", "category": "REFUND"},
    {"instruction": "I'm waiting for a restitution of {{Refund Amount}} dollars", "intent": "track_refund", "category": "REFUND"},
    {"instruction": "I want to know if there are any news on my refund", "intent": "track_refund", "category": "REFUND"},
    {"instruction": "I expect an refund of {{Refund Amount}} dollars", "intent": "track_refund", "category": "REFUND"},
    {"instruction": "where do I check the reimbursement current status?", "intent": "track_refund", "category": "REFUND"},
    {"instruction": "check if there is anything wrong with my damn restitution", "intent": "track_refund", "category": "REFUND"},
    {"instruction": "I'm waiting for a restitution of {{Refund Amount}} dollars", "intent": "track_refund", "category": "REFUND"},
    {"instruction": "i expect a rebate of {{Currency Symbol}}{{Refund Amount}}", "intent": "track_refund", "category": "REFUND"},
    {"instruction": "help checking if there is anything new on the bloody rebate", "intent": "track_refund", "category": "REFUND"},
]
